[project]
name = "ibm"
version = "0.1.0"
description = ""
authors = [
    {name = "its_catinsauce",email = "brian@klinklin..ai"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "notebook (>=7.3.2,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
